## BOARD CONSTANTS ##

global ROWS
ROWS = 5
global COLS
COLS = 6

global ORB_DROP_DELAY
ORB_DROP_DELAY = 100 #millis

global DEFAULT_SWAPS_ALLOTED
DEFAULT_SWAPS_ALLOTED = 16

##global DEFAULT_TIME_ALLOTED_TO_SWAP
##DEFAULT_TIME_ALLOTED_TO_SWAP = 3000 #millis

### START GLOBAL CONSTANTS ###
global FPS
FPS = 30

global DUNGEON_AREA_SCREEN_HEIGHT
DUNGEON_AREA_SCREEN_HEIGHT      = 256
global MONSTER_TEAM_AREA_SCREEN_HEIGHT
MONSTER_TEAM_AREA_SCREEN_HEIGHT = 64


global ORB_WIDTH
ORB_WIDTH  = 40
global ORB_HEIGHT
ORB_HEIGHT = 40

global ORB_VERTICAL_SPACING
ORB_VERTICAL_SPACING   = 4
global ORB_HORIZONTAL_SPACING
ORB_HORIZONTAL_SPACING = 4

global ORB_MOUSE_AREA_WIDTH
ORB_MOUSE_AREA_WIDTH  = ((ORB_WIDTH  * COLS) + (ORB_HORIZONTAL_SPACING * COLS))
global ORB_MOUSE_AREA_HEIGHT
ORB_MOUSE_AREA_HEIGHT = ((ORB_HEIGHT * ROWS) + (ORB_VERTICAL_SPACING   * ROWS))

global FRAME_OFFSET
FRAME_OFFSET = 32

global ORBS_START_X_OFFSET
ORBS_START_X_OFFSET    = FRAME_OFFSET
global ORBS_START_Y_OFFSET
ORBS_START_Y_OFFSET    = FRAME_OFFSET + DUNGEON_AREA_SCREEN_HEIGHT + MONSTER_TEAM_AREA_SCREEN_HEIGHT
global ORBS_END_X_OFFSET
ORBS_END_X_OFFSET      = ORBS_START_X_OFFSET + ORB_MOUSE_AREA_WIDTH
global ORBS_END_Y_OFFSET
ORBS_END_Y_OFFSET      = ORBS_START_Y_OFFSET + ORB_MOUSE_AREA_HEIGHT


global BOARD_ORB_FRAME_IMAGE_OFFSET
BOARD_ORB_FRAME_IMAGE_OFFSET = 16
global BOARD_ORB_FRAME_IMAGE_WIDTH
BOARD_ORB_FRAME_IMAGE_WIDTH = ORB_MOUSE_AREA_WIDTH + BOARD_ORB_FRAME_IMAGE_OFFSET
global BOARD_ORB_FRAME_IMAGE_HEIGHT
BOARD_ORB_FRAME_IMAGE_HEIGHT = ORB_MOUSE_AREA_HEIGHT + BOARD_ORB_FRAME_IMAGE_OFFSET
global BOARD_ORB_FRAME_START_X_OFFSET
BOARD_ORB_FRAME_START_X_OFFSET = ORBS_START_X_OFFSET - BOARD_ORB_FRAME_IMAGE_OFFSET/2
global BOARD_ORB_FRAME_START_Y_OFFSET
BOARD_ORB_FRAME_START_Y_OFFSET = ORBS_START_Y_OFFSET - BOARD_ORB_FRAME_IMAGE_OFFSET/2

global FONT_TYPE
FONT_TYPE = "monospace"
global FONT_SIZE
FONT_SIZE = 14
global HEALTH_BAR_FONT_SIZE
HEALTH_BAR_FONT_SIZE = 12

global HEALTH_BAR_HEIGHT
HEALTH_BAR_HEIGHT = 12
global HEALTH_BAR_WIDTH
HEALTH_BAR_WIDTH = ORB_MOUSE_AREA_WIDTH
global HEALTH_BAR_START_X_OFFSET
HEALTH_BAR_START_X_OFFSET = ORBS_START_X_OFFSET
global HEALTH_BAR_START_Y_OFFSET
HEALTH_BAR_START_Y_OFFSET = FRAME_OFFSET + DUNGEON_AREA_SCREEN_HEIGHT

global HEALTH_BAR_BACKGROUND_COLOR
HEALTH_BAR_BACKGROUND_COLOR = (80,80,80,40)
global HEALTH_BAR_COLOR
HEALTH_BAR_COLOR            = (220,45,45)
global HEALTH_BAR_TEXT_COLOR
HEALTH_BAR_TEXT_COLOR       = (255,255,255)
global INFO_TEXT_COLOR
INFO_TEXT_COLOR             = (255,255,255)

global MONSTER_TEAM_SINGLE_MONSTER_WIDTH
MONSTER_TEAM_SINGLE_MONSTER_WIDTH = 40
global MONSTER_TEAM_SINGLE_MONSTER_HEIGHT
MONSTER_TEAM_SINGLE_MONSTER_HEIGHT = 40
global MONSTER_TEAM_SPACER
MONSTER_TEAM_SPACER = 4
global MONSTER_TEAM_MAX_WIDTH
MONSTER_TEAM_MAX_WIDTH = HEALTH_BAR_WIDTH
global MONSTER_TEAM_START_X_OFFSET
MONSTER_TEAM_START_X_OFFSET = ORBS_START_X_OFFSET
global MONSTER_TEAM_START_Y_OFFSET
MONSTER_TEAM_START_Y_OFFSET = HEALTH_BAR_START_Y_OFFSET + HEALTH_BAR_HEIGHT + MONSTER_TEAM_SPACER

global SCREEN_WIDTH
SCREEN_WIDTH  = (ORBS_START_X_OFFSET * 2) + (ORB_WIDTH * COLS) + (ORB_HORIZONTAL_SPACING * COLS)
global SCREEN_HEIGHT
SCREEN_HEIGHT = DUNGEON_AREA_SCREEN_HEIGHT + MONSTER_TEAM_AREA_SCREEN_HEIGHT + (FRAME_OFFSET * 2) + (ORB_HEIGHT * ROWS) + (ORB_VERTICAL_SPACING   * ROWS)
##global ORB_AREA_BLOCK_WIDTH
##ORB_AREA_BLOCK_WIDTH = ORB_WIDTH + ORB_HORIZONTAL_SPACING
##global ORB_AREA_BLOCK_HEIGHT
##ORB_AREA_BLOCK_HEIGHT = ORB_HEIGHT + ORB_VERTICAL_SPACING

global ENEMY_WIDTH
ENEMY_WIDTH = SCREEN_WIDTH - FRAME_OFFSET*2
global ENEMY_HEIGHT
ENEMY_HEIGHT = DUNGEON_AREA_SCREEN_HEIGHT - FRAME_OFFSET
global ENEMY_X_POS
ENEMY_X_POS = FRAME_OFFSET
global ENEMY_Y_POS
ENEMY_Y_POS = FRAME_OFFSET

global ENEMY_INFO_Y_POS
ENEMY_INFO_Y_POS = FRAME_OFFSET/2

global ENEMY_ATTACK_COUNTDOWN_X_POS
ENEMY_ATTACK_COUNTDOWN_X_POS = FRAME_OFFSET/2
global COUNTDOWN_BOX_WIDTH
COUNTDOWN_BOX_WIDTH = FRAME_OFFSET/2
global COUNTDOWN_BOX_HEIGHT
COUNTDOWN_BOX_HEIGHT = FRAME_OFFSET/2

global SECONDS_TO_DISPLAY_HEALTH_CHANGE
SECONDS_TO_DISPLAY_HEALTH_CHANGE = 3

global SECONDS_TO_FADE
SECONDS_TO_FADE = 5
### END GLOBAL CONSTANTS ###
